### ISSUE TITLE
Smooth scrolling breaks visual mode

### ISSUE THREAD

**Issue by fatih** [terryma/vim-smooth-scroll#1]
Normally when we select a line (via `V`) than we can increase the selection via ctrl+d and ctrl+u. However this plugin breaks this behaviour. We are no more able to select lines in visual mode. Because vim-smooth-scrool disables visual mode as soon as we use on of the  `calls`.

**Comment by jordwalke** [comment]
I noticed this too.

**Comment by ZiYang-oyxy** [comment]
Caused by :redraw. Are there any solutions?

**Comment by lucasicf** [comment]
@fatih 
@hh123okbb 
@jordwalke 

mapping the commands with `nnoremap` instead of `noremap`
I even suggest changing the documentation, because there's no benefit of this outside of the normal mode.

**Comment by silouanwright** [comment]
@lucasicf I don't believe it works when you change the mappings like that in the .vimrc

**Comment by lucasicf** [comment]
@rey-wright it worked successfully for me... can you try and see whether it works for you too? it'll be helpful to validate this solution. thanks
