### ISSUE TITLE
Counts bork the scrolls

### ISSUE THREAD

**Issue by Olivia5k** [terryma/vim-smooth-scroll#8]
`50<c-d>` will make the screen flicker really badly for a while, and then it ends 49 rows below the destination that a single `<c-d>` would've gotten.

**Comment by craftyguy** [comment]
Since this project seems abandoned, I forked it and implementing handling of counts. You can get the patch here: https://github.com/craftyguy/vim-smooth-scroll/commit/31d5ee89dab6cfb9289047b8c0ceee660db18127
